name: Entregables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        if: runner.os == 'Windows'
        run: .\\venv\\Scripts\\activate
      - name: Paso 4 - Activar entorno virtual 
        if: runner.os != 'Windows'
        run: source venv/bin/activate

      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 6 - Instalar dependencias
        run: pip install -r requirements.txt  

      - name: Paso 7 - Ejecutar Script
        run: python src/edu_bigdata/main.py habitantes.csv

      - name: Paso 8 - Subir base de datos como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: database
          path: src/edu_bigdata/static/db/habitantes_de_calle.db
        if: success()
